Enemy path
Nicklason/4-semester-project pull request #45
Opened 2021-04-05 20:51 UTC by stped18

enemy part 
and som changes for Nicklas

2021-04-05 22:21 UTC, Nicklason requested changes

2021-04-05 22:21 UTC, Nicklason commented on dk.sdu.se4.common/src/main/java/dk/sdu/se4/common/entity/part/LifePart.java
>      public void setMAX_HIT_POINTS(int MAX_HIT_POINTS) {
Still not camel case :)

2021-04-07 13:11 UTC, stped18 commented on dk.sdu.se4.common/src/main/java/dk/sdu/se4/common/entity/part/LifePart.java
>      public void setMAX_HIT_POINTS(int MAX_HIT_POINTS) {
it is fixt

2021-04-07 14:36 UTC, Nicklason commented on dk.sdu.se4.common/src/main/java/dk/sdu/se4/common/entity/part/LifePart.java
>      public void setMAX_HIT_POINTS(int MAX_HIT_POINTS) {
It is not camel case, it is snake case.

2021-04-08 09:42 UTC, Nicklason approved these changes

2021-04-08 09:47 UTC, Kjalris approved these changes

2021-04-08 09:49 UTC, merged

2021-04-08 09:54 UTC, DenBedste reviewed
Looks good