Bullet component
Nicklason/4-semester-project pull request #53
Opened 2021-04-11 06:29 UTC by DenBedste

2021-04-11 06:34 UTC, DenBedste commented
Check failed caused by PositionPart constructor now taking (int x, int y) opossed to (Point(x, y))

2021-04-11 09:47 UTC, stped18 approved these changes

2021-04-11 09:50 UTC, Kjalris approved these changes

2021-04-11 10:39 UTC, Nicklason requested changes

2021-04-11 10:39 UTC, Nicklason commented on .gitignore
> +/dk.sdu.se4.map/nbproject/
Don't do this.

2021-04-11 10:39 UTC, Nicklason commented on dk.sdu.se4.Equipment/pom.xml
> +    <bundle.namespace>dk.sdu.se4.Equipment</bundle.namespace>
Use lowercase name

2021-04-11 10:39 UTC, Nicklason commented on dk.sdu.se4.Equipment/pom.xml
> +  <artifactId>dk.sdu.se4.Equipment</artifactId>
Use lowercase name

2021-04-11 10:39 UTC, Nicklason commented on dk.sdu.se4.Equipment/src/main/java/dk/sdu/se4/Equipment/Bullet.java
> +package dk.sdu.se4.Equipment;
Use lowercase name

2021-04-11 10:39 UTC, Nicklason commented on dk.sdu.se4.Equipment/src/main/java/dk/sdu/se4/Equipment/BulletPlugin.java
> +package dk.sdu.se4.Equipment;
Use lowercase name

2021-04-11 10:39 UTC, Nicklason commented on dk.sdu.se4.Equipment/src/main/java/dk/sdu/se4/Equipment/BulletPlugin.java
> +            System.out.println("mapservice null load");
Remove print

2021-04-11 10:39 UTC, Nicklason commented on dk.sdu.se4.Equipment/src/main/java/dk/sdu/se4/Equipment/BulletPlugin.java
> +            System.out.println("mapservice null unload");
Remove print

2021-04-11 10:39 UTC, Nicklason commented on dk.sdu.se4.Equipment/src/main/java/dk/sdu/se4/Equipment/BulletProcessor.java
> +package dk.sdu.se4.Equipment;
Use lowercase name

2021-04-11 10:39 UTC, Nicklason commented on dk.sdu.se4.Equipment/src/main/java/dk/sdu/se4/Equipment/BulletProcessor.java
> +                movingPart.setMovingLeft(false);
Always shoot a bullet up?

2021-04-11 10:39 UTC, Nicklason commented on dk.sdu.se4.Equipment/src/main/java/dk/sdu/se4/Equipment/EquipmentCore.java
> +        System.out.println("ADDED MapService TO Bullet "+this.mapService.getClass().toString());
Remove print

2021-04-11 10:39 UTC, Nicklason commented on dk.sdu.se4.Equipment/src/main/java/dk/sdu/se4/Equipment/EquipmentCore.java
> +        System.out.println("REMOVED MapService FROM Bullet "+this.mapService.getClass().toString());
Remove print

2021-04-11 10:39 UTC, Nicklason commented on dk.sdu.se4.Equipment/src/main/resources/META-INF/EquipmentPlugin.xml
> +    <implementation class="dk.sdu.se4.Equipment.BulletPlugin"/>
Use lowercase name

2021-04-11 10:39 UTC, Nicklason commented on dk.sdu.se4.Equipment/src/main/resources/META-INF/EquipmentProcessor.xml
> +    <implementation class="dk.sdu.se4.Equipment.BulletProcessor"/>
Use lowercase name

2021-04-11 10:39 UTC, Nicklason commented on dk.sdu.se4.common/src/main/java/dk/sdu/se4/common/entity/part/TimePart.java
> +public class TimePart implements EntityPart {
Add comments. What is "time" and why is it a float?

2021-04-11 10:39 UTC, Nicklason commented on pom.xml
> +    <module>dk.sdu.se4.Equipment</module>
Use lowercase name

2021-04-11 10:40 UTC, Nicklason commented
Why did you delete the test?

2021-04-12 15:57 UTC, Nicklason approved these changes

2021-04-12 15:57 UTC, merged