Add CollisionService
Nicklason/4-semester-project pull request #60
Opened 2021-04-12 15:40 UTC by Nicklason

Add collision service implemented using grids.

Splits the entire game map into grids and detects collision inside of each grid.

2021-04-12 15:59 UTC, Kjalris approved these changes

2021-04-12 20:27 UTC, DenBedste approved these changes

2021-04-13 07:14 UTC, stped18 requested changes

2021-04-13 07:14 UTC, stped18 commented on dk.sdu.se4.bullet/src/main/java/dk/sdu/se4/bullet/Bullet.java
> +        super(true);
what is this
use an part insted

2021-04-13 07:14 UTC, stped18 commented on dk.sdu.se4.common/src/main/java/dk/sdu/se4/common/entity/Entity.java
> +    public Entity(boolean friendly) {
User an part insted

2021-04-13 07:14 UTC, stped18 commented on dk.sdu.se4.common/src/main/java/dk/sdu/se4/common/entity/Entity.java
> +    public boolean isFriendly() {
create TypePart and use that :) the project is based on parts

2021-04-13 18:22 UTC, Nicklason commented on dk.sdu.se4.bullet/src/main/java/dk/sdu/se4/bullet/Bullet.java
> +        super(true);
Yeah my bad

2021-04-13 18:25 UTC, Nicklason commented
I don't know why but this pull request was made as a draft because we were not done working, but it is now open for some reason. I will close it and make a new pull request when it is ready to merge.

2021-04-13 18:25 UTC, closed without merging