weapon fire rate and reloading
Nicklason/4-semester-project pull request #78
Opened 2021-04-25 03:21 UTC by DenBedste

2021-04-27 19:09 UTC, stped18 approved these changes

2021-04-28 09:28 UTC, Kjalris approved these changes

2021-04-28 15:26 UTC, Nicklason requested changes

2021-04-28 15:26 UTC, Nicklason commented on dk.sdu.se4.weapon/src/main/java/dk/sdu/se4/weapon/WeaponProcessor.java
> -                            System.out.println("out of bullets");
Remove print

2021-04-28 15:26 UTC, Nicklason commented on dk.sdu.se4.weapon/src/main/java/dk/sdu/se4/weapon/WeaponProcessor.java
> +                            System.out.println(tp.getTime());
Remove print

2021-04-29 12:21 UTC, Lucassass approved these changes

2021-04-29 21:41 UTC, Nicklason approved these changes

2021-04-30 07:29 UTC, stped18 approved these changes

2021-05-03 11:23 UTC, frederikstroem approved these changes

2021-05-18 17:30 UTC, closed without merging

2021-05-18 17:30 UTC, Kjalris commented
We fix this already